config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } 
  #controllers: { sessions: 'devise/sessions' }
  
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  
  resources :categories, only: [:show]
  
  resources :orders, only: [:show, :edit, :update] do
    post :add_book, on: :collection
  end
  
  resources :order_books, only: [:destroy]
  resources :checkout, only: [:index, :show, :update]
  
  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart/empty', to: 'orders#empty_cart', as: :empty_cart
  
  resource :user do
    patch 'update_password'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :orders
  has_many :reviews
  
  belongs_to :billing_address, class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'
  accepts_nested_attributes_for :billing_address
  accepts_nested_attributes_for :shipping_address
  
  validates :email, presence: true
  
  def billing_address
    super || Address.new
  end

  def shipping_address
    super || Address.new
  end
  
  def self.from_omniauth(auth)
    user = find_by(provider: auth.provider, uid: auth.uid.to_s)
    return user if user
    
    email = auth.info[:email]
    user = find_by(email: email)
    
    if user
      user.update_attributes(provider: auth.provider, uid: auth.uid.to_s)
    else
      user = create(email: email, provider: auth.provider, uid: auth.uid.to_s)
    end
  end
  
  def password_required?
    super && provider.blank?
  end
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_action :configure_sign_in_params, only: [:create]

#  GET /resource/sign_in
  def new
    flash[:notice] = "TEST"
    #super
  end

#  POST /resource/sign_in
  def create
    super
  end

#  DELETE /resource/sign_out
  def destroy
    super
  end

  protected

#  If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, except: [:show]
  
  def show
    @history = OrderHistory.new(current_user)
  end
  
  def edit
  end

  def update
    assign_address_to_user
    if @user.update(user_params)
      flash[:notice] = t('user.flashes.account_updated')
      redirect_to edit_user_path
    else
      render :edit
    end
  end
  
  def update_password
    if @user.update_with_password(user_params)
      sign_in @user, bypass: true
      flash[:notice] = t('user.flashes.password_updated')
      redirect_to edit_user_path
    else
      render :edit
    end
  end
  
  private
  
  def assign_address_to_user
    case user_params.keys[0]
    when 'billing_address_attributes'
      @user.billing_address = Address.create(user_params['billing_address_attributes'])
    when 'shipping_address_attributes'
      @user.shipping_address = Address.create(user_params['shipping_address_attributes'])
    end
  end
  
  def find_user
    @user = current_user    
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :current_password,
      billing_address_attributes: address_attributes,
      shipping_address_attributes: address_attributes
    )
  end
  
  def address_attributes
    %i(id first_name last_name address zip city phone country_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def error_messages_for(target, attr = 'all')
    errors = find_errors_for(target, attr)
    return '' if errors.empty?

    messages = errors.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger">
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  private

  def find_errors_for(target, attr)
    return target.errors.full_messages if attr == 'all'
    target.errors.full_messages.select {|msg| msg =~ /#{attr}/i }
  end
end

app/views/users/_form.html.haml
.row
  .col-md-6
    = form_for(@user, url: { action: :update }) do |f|
      %h3.page-header= t('user.settings.billing_address')

      = error_messages_for(@user.billing_address)
      = f.fields_for :billing_address do |bill_form|
        = render('address/form', f: bill_form)
      = f.submit t('user.settings.save'), class: "btn btn-primary"

  .col-md-6
    = form_for(@user, url: { action: :update }) do |f|
      %h3.page-header= t('user.settings.shipping_address')

      = error_messages_for(@user.shipping_address)
      = f.fields_for :shipping_address do |bill_form|
        = render('address/form', f: bill_form)
      = f.submit t('user.settings.save'), class: "btn btn-primary"
.row
  .col-md-6
    = form_for(@user, url: { action: :update }) do |f|
      %h3.page-header= t('user.settings.email')

      = error_messages_for(@user, 'email')
      .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control'
      = f.submit t('user.settings.save'), class: "btn btn-primary"

  .col-md-6
    = form_for(@user, url: { action: :update_password }) do |f|
      %h3.page-header= t('user.settings.password')

      = error_messages_for(@user, 'password')
      .form-group
        = f.label :password
        = f.password_field :password, :autocomplete => 'off', class: 'form-control'
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control'
      - if f.object.encrypted_password.present?
        .form-group
          = f.label :current_password
          = f.password_field :current_password, class: 'form-control'
      = f.submit t('user.settings.save'), class: "btn btn-primary"
.row
  .col-md-6
    %h3.page-header= t('user.settings.remove_account') 
    = button_to(t('user.settings.cancel_account'), registration_path(@user), 
              class: 'btn btn-danger', data: { confirm: "Are you sure?" }, method: :delete)

app/views/users/edit.html.haml
.container
  %h1=t('user.settings.settings')
  = render('form')

app/views/users/show.html.haml
.container
  .row
    %h1= t('h .orders.orders')
    
    %h3.page-header= t('user.orders.in_progress')
    - if @history.orders_in_progress.empty?
      %p= t('user.orders.empty_in_progress')
    - else
      = render('orders/order_in_progress', order: @history.orders_in_progress)
      = link_to t('user.orders.go_to_cart'), cart_path, class: 'btn btn-success'
    
    %h3.page-header= t('user.orders.in_queue')
    - if @history.orders_in_queue.empty?
      %p= t('user.orders.empty_completed')
    - else
      = render('orders/order_details', orders: @history.orders_in_queue)
    
    %h3.page-header= t('user.orders.in_delivery')
    - if @history.orders_in_delivery.empty?
      %p= t('user.orders.empty_completed')
    - else
      = render('orders/order_details', orders: @history.orders_in_delivery)
    
    %h3.page-header= t('user.orders.delivered')
    - if @history.orders_delivered.empty?
      %p= t('user.orders.empty_completed')
    - else
      = render('orders/order_details', orders: @history.orders_delivered)