config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } 
  #controllers: { sessions: 'devise/sessions' }
  
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  
  resources :categories, only: [:show]
  
  resources :orders, only: [:show, :edit, :update] do
    post :add_book, on: :collection
  end
  
  resources :order_books, only: [:destroy]
  resources :checkout, only: [:index, :show, :update]
  
  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart/empty', to: 'orders#empty_cart', as: :empty_cart
  
  resource :user do
    patch 'update_password'
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  
  belongs_to :user
  belongs_to :credit_card
  belongs_to :billing_address,  class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'
  belongs_to :shipment
  belongs_to :coupon
  has_many   :order_books, dependent: :destroy
  
  accepts_nested_attributes_for :order_books
  
  #validates :user,  presence: true, uniqueness: true
  validates :state, presence: true
  
  before_validation :set_coupon, if: 'code.present?'
  after_update :update_order
  
  attr_accessor :code
  
  delegate :clear, :empty?, to: :order_books
  delegate :discount,       to: :coupon,      prefix: true, allow_nil: true
  # delegate :name,           to: :shipment,    prefix: true, allow_nil: true
  
  aasm column: :state, whiny_transitions: false do
    state :in_progress, initial: true
    state :in_queue, after_enter: :set_time_and_ref
    state :in_delivery
    state :delivered
    state :canceled
    
    event :create_order do
      transitions from: :in_progress, to: :in_queue
    end
    
    event :shipment do
      transitions from: :in_queue, to: :in_delivery
    end
    
    event :shipped do
      transitions from: :in_delivery, to: :delivered
    end

    event :reject do
      transitions from: [:in_progress, :in_queue], to: :canceled
    end    
  end
  
  def self.in_progress
    find_by(state: 'in_progress')
  end
    
  def add_to_order(book, quantity = 1)
    order_book = order_books.find_by(book: book)
    if order_book
      order_book.quantity += quantity
      order_book.save
    else
      order_books.create(price: book.price, quantity: quantity, book: book)
    end
    update_order
  end
  
  def update_order
    update_columns(
      total: calculate_price.total,
      subtotal: calculate_price.books_total,
      shipment_total: calculate_price.shipment_total
    )
  end
  
  def set_time_and_ref
    touch(:completed_at)  
    update(ref: ref_order)
  end
  
  def set_coupon
    coupon = Coupon.find_by(code: code)
    if coupon && coupon.active?
      self.coupon_id = coupon.id
    else
      errors.add(:base, 'Invalid coupon code')
    end
  end
  
  private
  
  def ref_order
    'R-%.6d' % id
  end
  
  def calculate_price
    @calculator ||= OrderCalculation.new(self)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :check_order_in_progress, only: [:edit, :update]
  
  def show
    @order = Order.find(params[:id]).decorate
  end
  
  def edit
  end
  
  def add_book
    book = Book.find(params[:book_id])
    quantity = params[:order][:quantity].to_i
    order_in_progress.add_to_order(book, quantity)
    redirect_to cart_path
  end
  
  def update
    if @order.update(order_params)
      if params.key?(:checkout)
        redirect_to checkout_index_path
      else
        redirect_to cart_path
      end
    else
      flash.now[:danger] = "Invalid coupon code."
      render 'edit'
    end
  end
  
  def empty_cart
    order_in_progress.clear
    redirect_to cart_path
  end
  
  private
  
  def check_order_in_progress
    @order = order_in_progress.decorate
  end
  
  def order_params
    params.require(:order).permit(:code, order_books_attributes: [:id, :quantity])
  end

end

app/views/orders/_form.html.haml
= form_for(@order) do |f|
  // = error_messages_for 'order'
  .table-responsive
    %table.table.cart
      %thead
        %tr
          %th.text-center{:colspan => "2"} Book
          %th Price
          %th Count
          %th{:colspan => "2"} Total
      %tbody
        = render partial: "order_book", collection: @order.order_books, locals: { f: f}
      %tfoot
        %tr
          %td{colspan: "4", align: "right"}
            %b Subtotal:
          %td= number_to_currency(@order.total)
      - if @order.coupon
        %tfoot
          %tr
            %td{colspan: "4", align: "right"}
              %b Discount:
            %td= number_to_currency(@order.coupon_discount)
  .box-footer
    .pull-left
      = link_to 'Empty cart', empty_cart_path, method: :patch, class: "btn btn-default"
      = link_to 'Continue shopping', books_path, class: "btn btn-default"
        
    .pull-right
      .form-inline
        = f.text_field :code, placeholder: 'Coupon code', class: 'form-control coupon'
        = f.submit 'Update', class: "btn btn-success update"
        = f.submit 'Checkout', name: 'checkout', class: "btn btn-primary checkout"

app/views/orders/_order_book.html.haml
= f.fields_for(:order_books, order_book) do |item_book|
  %tr
    %td
      = image_tag(order_book.book.image.thumb, class: 'img-responsive')
    %td
      = link_to(order_book.book_title, book_path(order_book.book_id))
    %td
      = number_to_currency(order_book.price)
    %td
      = item_book.number_field :quantity, min: 1, class: 'form-control'
    %td
      = number_to_currency(order_book.subtotal)
      = link_to order_book_path(order_book), method: :delete, class: 'delete' do
        %span.glyphicon.glyphicon-trash

app/views/orders/_order_books.html.haml
= f.fields_for(:order_books, order_book) do |item_form|
  %tr
    %td
      = order_book
    %td
      = link_to(order_book.book_title, book_path(order_book.book))
    %td
      = number_to_currency(order_book.price)
    %td
      = item_form.number_field :quantity, min: 1, class: 'form-control'
    %td
      = number_to_currency(order_book.subtotal)
      = link_to order_book_path(order_book), method: :delete, class: 'delete' do
        %span.glyphicon.glyphicon-trash

app/views/orders/_order_details.html.haml
.table-responsive
  %table.table.cart
    %thead
      %th= t('order.number')
      %th= t('order.completed_at')
      %th= t('order.total')
    %tbody
      - orders.each do |order|
        %tr
          %td= order.ref
          %td= order.completed_at
          %td= number_to_currency(order.total)
          %td= link_to(t('order.view'), order)

app/views/orders/_order_in_progress.html.haml
.table-responsive
  %table.table.cart
    %thead
      %tr
        %th.text-center{:colspan => "2"} Book
        %th= t('order.price')
        %th= t('order.quantity')
        %th= t('order.total')
    %tbody
      - order.order_books.each do |order_book|
        %tr
          %td
            = image_tag(order_book.book.image.thumb, class: 'img-responsive')
          %td
            = link_to(order_book.book_title, book_path(order_book.book))
          %td
            = number_to_currency(order_book.price)
          %td
            = order_book.quantity
          %td
            = number_to_currency(order_book.subtotal)

    %tfoot
      %tr
        %td{colspan: "4", align: "right"}
          %b= t('order.order_total')
        %td= number_to_currency(order.total)

    %tfoot
      %tr
        %td{colspan: "4", align: "right"}
          %b= t('order.subtotal')
        %td= number_to_currency(order.subtotal)
    - if order.coupon
      %tfoot
        %tr
          %td{colspan: "4", align: "right"}
            %b= t('order.discount')
          %td= number_to_currency(order.coupon_discount)

    %tfoot
      %tr
        %td{colspan: "4", align: "right"}
          %b= t('order.shipping')
        %td= number_to_currency(order.shipment_total)

app/views/orders/edit.html.haml
= provide(:title, 'Shopping cart')
.container
  #basket
    .box
      %h1 Shopping cart
      - if @order.empty?
        .alert.alert-info Your cart is empty
        = link_to 'Continue shopping', books_path, class: "btn btn-default"
      - else
        = render('form')

app/views/orders/show.html.haml
.container
  %h1 
    Order
    = @order.ref
  = render('shared/order_details', order: @order)