config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } 
  #controllers: { sessions: 'devise/sessions' }
  
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  
  resources :categories, only: [:show]
  
  resources :orders, only: [:show, :edit, :update] do
    post :add_book, on: :collection
  end
  
  resources :order_books, only: [:destroy]
  resources :checkout, only: [:index, :show, :update]
  
  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart/empty', to: 'orders#empty_cart', as: :empty_cart
  
  resource :user do
    patch 'update_password'
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, :price, :in_stock, presence: true
  delegate  :full_name, to: :author, prefix: true, allow_nil: true
  
  has_many :author
  belongs_to :category
  has_many :reviews
  has_many :order_books
  
  mount_uploader :image, ImageUploader  
  paginates_per 9

  def self.best_books
    joins(:order_books)
      .select('books.*, sum(order_books.quantity) as qty')
      .group(:id)
      .order('qty DESC')
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :get_categories

  def index
    @books = Book.page(params[:page])
  end

  def show
    @book = Book.find(params[:id]).decorate
  end
end

app/views/books/_add_book.html.haml
.col-sx-6
  = form_for :order, url: add_book_orders_path, class: 'form-inline cart_item_form' do |f|
    .form-group
      = hidden_field_tag :book_id, book.id
      = f.label :quantity, t('cart.quantity')
      = f.number_field :quantity, value: 1, min: 1, class: 'form-control'
    = f.submit('ADD TO CART', class:"btn btn-primary")

app/views/books/_book.html.haml
.col-sm-3.col-lg-3.col-md-3
  .thumbnail
    = image_tag(book.image.thumb)
    .caption
      %h4.book= link_to(book.title, book)
      %h4= number_to_currency(book.price)

app/views/books/_cart_form.html.haml
= form_for :order, url: add_book_orders_path, html: { class: 'form-inline cart_item_form' } do |f|
  .form-group
    = hidden_field_tag :book_id, book.id
    = f.number_field :quantity, value: 1, min: 1, class: 'form-control quantity'
  = f.submit(t('cart.add_to_cart'), class:"btn btn-primary add-book")

app/views/books/index.html.haml
= provide(:title, 'Shop')
.container
  .row
    .col-md-9
      %h1 Shop
      = render @books
      = paginate @books
    .col-md-3
      = render 'categories/category_list'

app/views/books/show.html.haml
= provide(:title, @book.title)
.container
  .row
    .col-xs-4
      = image_tag(@book.image, class: 'img-responsive preview')
    .col-xs-8  
      .caption-full
        %h1.title= @book.title
        %span.author by #{@book.author_name}
        %p= @book.full_description
        %p.price-p
          %span.price Price:
          = number_to_currency(@book.price)
          = render('books/cart_form', book: @book)
  .row
    .text-left
      %h3.col-sx-12 Reviews
      .span= link_to('Leave a Review', new_book_review_path(@book), class: 'btn btn-success')
    %hr/
    - @book.reviews.each do |review|
      .row
        .col-md-12
          = render_star(review.rating)
          %span.pull-right= time_tag(review.created_at.to_date)
          %p by #{review.user.email}
          %p= review.text_review
      %hr/