config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' } 
  #controllers: { sessions: 'devise/sessions' }
  
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
  
  resources :categories, only: [:show]
  
  resources :orders, only: [:show, :edit, :update] do
    post :add_book, on: :collection
  end
  
  resources :order_books, only: [:destroy]
  resources :checkout, only: [:index, :show, :update]
  
  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart/empty', to: 'orders#empty_cart', as: :empty_cart
  
  resource :user do
    patch 'update_password'
  end
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "The Bookstore", root_path, id: "logo"
    %ul.nav.navbar-nav.navbar-left
      %li.home= link_to "HOME", root_path
      %li.shop= link_to "SHOP", books_path
      %li.cart= render('shared/cart')
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li.settings= link_to "Settings", edit_user_path
        %li.orders= link_to "Orders",  user_path
        %li= link_to 'Sign out', destroy_user_session_path, :method => :delete
    - else 
      %ul.nav.navbar-nav.navbar-right
        %li.sign-in= link_to "Sign in", new_user_session_path 
        %li.sign-up= link_to "Sign up", new_user_registration_path
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=	full_title(yield(:title))	%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=	render 'layouts/header' %>
<br><br><br>
<%= yield(:navigation) %>
<%=	render 'shared/messages' %>
<%= yield %>

</body>
</html>